[2023-08-10 13:15:10,765] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\OneDrive\Masaüstü\project\cloud-intern-project\application\userland\controllers\user_controller.py", line 22, in sign_in
    return jsonify(response.__dict__)
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__dict__'
[2023-08-10 13:52:00,169] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\OneDrive\Masaüstü\project\cloud-intern-project\application\userland\controllers\user_controller.py", line 22, in sign_in
    return jsonify(response.__dict__)
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__dict__'
