[2023-08-24 11:54:38,544] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 11:55:54,277] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 11:59:10,530] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 11:59:53,986] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\OneDrive\Masaüstü\project\cloud-intern-project\application\userland\controllers\user_controller.py", line 31, in sign_in
    login_user(user, remember=remember)
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 180, in login_user
    if not force and not user.is_active:
                         ^^^^^^^^^^^^^^
AttributeError: type object 'user' has no attribute 'is_active'
[2023-08-24 12:00:49,738] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\OneDrive\Masaüstü\project\cloud-intern-project\application\userland\controllers\user_controller.py", line 33, in sign_in
    login_user(user, remember=remember)
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 180, in login_user
    if not force and not user.is_active:
                         ^^^^^^^^^^^^^^
AttributeError: type object 'user' has no attribute 'is_active'
[2023-08-24 12:10:05,185] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 13:42:07,337] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 13:46:20,603] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 13:50:27,425] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 14:29:51,032] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 15:18:05,728] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 15:23:40,773] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 15:27:02,242] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 15:35:18,866] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 18:00:18,293] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 18:01:40,743] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 18:01:44,876] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 18:09:11,473] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 18:24:09,008] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 18:24:17,058] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 18:27:11,738] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 18:31:02,359] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/sign_in C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /sign_in [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 178, in make_response
    return current_app.make_response(args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a BaseResponse.
[2023-08-24 18:33:12,096] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 18:35:07,818] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 18:39:33,216] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 18:43:30,786] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 18:54:32,875] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 19:16:36,079] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 19:17:27,194] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 19:28:07,749] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'application/frontend/src/views/LoginView.vue'. Did you mean 'userland.sign_in' instead?
[2023-08-24 19:41:13,554] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\OneDrive\Masaüstü\project\cloud-intern-project\application\userland\controllers\domain_controller.py", line 18, in get_search_detail_domain
    return render_template('result.html', response=response, keyword=keyword, name=current_user.name)
                                                                                   ^^^^^^^^^^^^^^^^^
AttributeError: 'Users' object has no attribute 'name'
[2023-08-24 19:41:13,565] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\OneDrive\Masaüstü\project\cloud-intern-project\application\userland\controllers\domain_controller.py", line 18, in get_search_detail_domain
    return render_template('result.html', response=response, keyword=keyword, name=current_user.name)
                                                                                   ^^^^^^^^^^^^^^^^^
AttributeError: 'Users' object has no attribute 'name'
[2023-08-24 19:41:21,755] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\OneDrive\Masaüstü\project\cloud-intern-project\application\userland\controllers\domain_controller.py", line 18, in get_search_detail_domain
    return render_template('result.html', response=response, keyword=keyword, name=current_user.name)
                                                                                   ^^^^^^^^^^^^^^^^^
AttributeError: 'Users' object has no attribute 'name'
[2023-08-24 19:41:26,305] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\OneDrive\Masaüstü\project\cloud-intern-project\application\userland\controllers\domain_controller.py", line 18, in get_search_detail_domain
    return render_template('result.html', response=response, keyword=keyword, name=current_user.name)
                                                                                   ^^^^^^^^^^^^^^^^^
AttributeError: 'Users' object has no attribute 'name'
[2023-08-24 19:41:38,257] ERROR 127.0.0.1 POST HTTP/1.1 http://127.0.0.1:5000/home C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py rt:0 Exception on /home [POST]
Traceback (most recent call last):
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\cloud-intern-project\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\enesk\OneDrive\Masaüstü\project\cloud-intern-project\application\userland\controllers\domain_controller.py", line 18, in get_search_detail_domain
    return render_template('result.html', response=response, keyword=keyword, name=current_user.name)
                                                                                   ^^^^^^^^^^^^^^^^^
AttributeError: 'Users' object has no attribute 'name'
